# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'MeepMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeepMap
  pod 'Swinject', '2.6.0'
  pod 'SwinjectStoryboard', '2.2.0'
  pod 'Moya/RxSwift', '15.0.0'
  pod 'GoogleMaps'
  pod 'SwiftLint'

  target 'MeepMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeepMapUITests' do
    # Pods for testing
  end

end
