# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'MeepMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeepMap
  pod 'RxSwift', '6.2.0'
  pod 'Swinject', '2.7.1'
  pod 'Moya/RxSwift', '15.0.0'
  pod 'GoogleMaps'

  target 'MeepMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeepMapUITests' do
    # Pods for testing
  end

end
